name: coastapp
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version, pip, and other very generic libraries
  - python=3.11
  - pip>=20
  - ca-certificates
  - certifi
  - openssl
  - boltons
  - ciso8601
  - cattrs

  # Development Tools
  - pre-commit
  - hatch

  # Jupyter
  - ipykernel

  # Interactive visualization libraries
  - bokeh
  - geoviews
  - holoviews
  - hvplot
  - ipyleaflet
  - ipympl
  - ipywidgets
  - jupyter_bokeh
  - matplotlib-base
  - panel
  - param

  # Data Science libraries
  - adlfs
  - cartopy
  - dask
  - fiona
  - fsspec
  - geopandas>=0.11.0
  - numpy
  - pandas
  - python-dotenv
  - rasterio
  - rioxarray
  - xarray
  - s3fs
  - pystac-client
  - pyperclip

  # Install the project and dependencies
  - pip:
      - duckdb  # Conda binaries are usually delayed
      # - -e .


