[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "coastapp"
version = "0.1.0"
description = "Coastal Typology Application"
authors = [{ name = "Floris Calkoen", email = "your-email@example.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]

[tool.ruff]
line-length = 88
src = ["src"]
target-version = "py311"
exclude = []
extend-ignore = [
  "E501",  # Line too long
  "E402",  # Module level import not at top of file
]

[tool.ruff.pydocstyle]
convention = "google"
